services:
  - type: web
    name: heart-disease-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PORT
        value: 10000
