services:
  - type: web
    name: heart-disease-app
    env: python
    repo: https://github.com/YetundeBadru/Design-and-Deployment-of-an-AI-Powered-Predictive-System
    branch: main
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    region: frankfurt
    plan: free
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
